name: Build Application
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.3"

      - name: Setup Conan
        uses: jwidauer/setup-conan@v1

      - name: Install C++ Dependencies
        run: |-
          conan profile detect
          conan install . --install=missing

      - name: Prepare CMake
        run: cmake . -DCMAKE_BUILD_TYPE=build/conan_toolchain.cmake

      - name: Compile Project
        run: cmake --build .
