name: Build Application
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.1"

      - name: Setup Conan
        uses: jwidauer/setup-conan@v1

      - name: Install C++ Dependencies
        run: |-
          conan profile detect
          conan install . --build=missing

      - name: Prepare CMake
        run: |-
          cmake build  . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=build/generators/conan_toolchain.cmake

      - name: Compile Project
        run: cmake --build .
